### PR TITLE
update_batch2

### PR DESCRIPTION
**Pull request by huilisabrina**
Hi @paturley ,

Here are some more updates that hope you can briefly review (the summary not the codes :)
- Added header conformers that converts external column names to internal names --> fixed the N/n issues;
- Beta/SE option is working now: If `--beta_name` and `--se_name` are both specified, then MTAG switches to the BETA/SE mode:
  - Sample size is still required, which along with beta/se, are used for munging;
  - The original N is used for sample size related filtering;
  - SE are standardized using the provided allele frequency SE_std = SE * sqrt( 2pq );
  - the MTAG analysis uses N = 1/(SE_std^2) as opposed to the raw N

While so far in testing alternating between Z/N and BETA/SE does not yield inconsistent results, I'm a bit worried that if the data does not satisfy N=1/(SE^2), the results will be still off. I tested using two small samples, as below:

(Using Z/N)
image

(Using BETA/SE)
image

Let me know if you have any comments, especially whether we should add any warning/messages for the BETA/SE option. Otherwise I can merge these updates to the master branch. 

Thanks!
Hui

### CODE REVIEW

**Comment by paturley** [comment]
I'm a bit confused. The two log files look pretty inconsistent to me. Are
the actual estimates comparable, however?

**Comment by huilisabrina** [comment]
@paturley , You're right the Omega's are very different. I was not comparing the tables carefully and looked at the sigma's near the end. For the actual estimates, I just made a few figures to compare the actual estimates:  `mtag_z` and `mtag_pval` are pretty consistent; but the `mtag_beta` and `mtag_se` are not very consistent.

zn_bs_trait_1_mtag_z
zn_bs_trait_1_mtag_pval
zn_bs_trait_1_mtag_beta
zn_bs_trait_1_mtag_se

Other possible reasons for this inconsistency is that since I used the UKB replication of SWB, DEP and NEUR as the testing sample, 1) the N's are hard coded numbers (uniform across SNPs), 2) N=1/SE^2 assumption does not hold in BOLT. Maybe I should try to find another testing sample?

**Comment by huilisabrina** [comment]
Did you mean to say unstandardized betas? I think the last step in MTAG before output is to unstandardize the betas. I just checked and this (unstandardization) step is the same between the two options. The only thing that contributes to the difference is that in the beta/se option, the N is backed out from SE (and freq). 

The following are for a single trait SWB, the pattern looks qualitatively similar to me: 
zn_bs_single_trait_mtag_beta
zn_bs_single_trait_mtag_se
zn_bs_single_trait_mtag_z
zn_bs_single_trait_mtag_pval

**Comment by paturley** [comment]
Standardized wrt the phenotype or genotype? What would be helpful to see is
how the single trait MTAG output compares to the GWAS input for the two
options.

**Comment by huilisabrina** [comment]
Hi @paturley ,

Ah I see what you're saying now. I meant the standardization wrt genotypes or the 2pq^0.5 factor. You're right that standardization is inconsistent between the two option. 

Comparing the input vs output in single-trait MTAG: (top is Z/N and bottom is Beta/SE)
zn_bs_inconsistent_std

To fix this, I changed N=1/(SE_std^2) to N=1/(SE^2), so removed the standardization of SE (see the initial comment above). The single traits results are closer to each other now - `mtag_beta` and `mtag_se` are both in unstandardized (genotype) units:
zn_bs_consistent_std

Best,
Hui

**Comment by paturley** [comment]
I'm a bit confused. I think the results looked fine before. My
understanding was that beta_ZN gave results corresponding to if the
phenotype had been standardized, which is why the beta of the GWAS input
and the MTAG output were different. On the other hand, I thought that the
beta_BS option maintains the same unit, so the beta of the GWAS input and
the MTAG output should be the same. This was the case originally, but it no
longer seems to be the case after your adjustment.

**Comment by huilisabrina** [comment]
I see, so you meant the standardization wrt phenotypes. I changed this back now, so the key (only) difference between the two options is: Z/N assumes the input gwas was done with standardized Y, but Beta/SE does not assume/require so. I somewhat think the latter is circular (i.e. we're still assuming SD(y)=1 implicitly). We can discuss this more in person. Thanks a lot for your help!

**Pull request merged**
